/* JFS AI — Tenant data bridge. Supabase is the source of truth. */
(function(){'use strict';
const SUPABASE_URL='https://evtkeyfjgqwarsmlzrkh.supabase.co';
const SUPABASE_KEY='sb_publishable_7lGio_RVVgkVASYYyBHQIg_GvL-8ELD';
const KEY='jfs_ai_tenants_cache_v6';
const FIRMAN={whatsapp1:'6281230633464',whatsapp2:'6285706050689',projectUrl:'https://jfsaitechnology.github.io/jfs-ai-platform/mas-firman-pratama/demo.html'};
let cache=[];try{cache=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){}
function save(){try{localStorage.setItem(KEY,JSON.stringify(cache))}catch(e){}}
function isFirman(t){return String(t?.tenant_code||'').toUpperCase()==='MAS-FIRMAN-PRATAMA'||String(t?.business_name||'').toLowerCase().includes('mas firman pratama')}
function normalize(t,s){return{id:t.id,name:t.business_name,type:t.business_type||'UMKM',whatsapp:t.whatsapp||'',whatsapp1:isFirman(t)?FIRMAN.whatsapp1:(t.whatsapp||''),whatsapp2:isFirman(t)?FIRMAN.whatsapp2:'',status:t.status||'inactive',aiEnabled:!!t.ai_enabled,plan:s?.plan_name||'-',startedAt:s?.start_date||null,expiresAt:s?.end_date||null,subscriptionStatus:s?.status||null,paymentStatus:s?.payment_status||null,projectUrl:isFirman(t)?FIRMAN.projectUrl:''}}
window.JFSTenantStore={all:()=>cache,get:id=>cache.find(t=>t.id===id),save:t=>{const i=cache.findIndex(x=>x.id===t.id);i>=0?cache[i]=t:cache.push(t);save();return t}};
function waButtons(t){if(!isFirman(t))return '';return '<div class="jfs-wa-buttons" style="display:flex;gap:7px;flex-wrap:wrap;margin-top:10px"><a class="btn wa" target="_blank" rel="noopener" href="https://wa.me/6281230633464?text=Halo%20Admin%20Mas%20Firman,%20saya%20ingin%20informasi%20lebih%20lanjut.">🟢 WA Admin 1</a><a class="btn wa" target="_blank" rel="noopener" href="https://wa.me/6285706050689?text=Halo%20Admin%20Mas%20Firman,%20saya%20ingin%20informasi%20lebih%20lanjut.">🟢 WA Admin 2</a></div>'}
window.installFirmanWhatsApp=function(){document.querySelectorAll('.tenant').forEach(card=>{if(!card.textContent.toLowerCase().includes('mas firman pratama'))return;card.querySelector('.jfs-wa-buttons')?.remove();card.insertAdjacentHTML('beforeend',waButtons({business_name:'Mas Firman Pratama'}))})};
window.JFS_REFRESH_TENANTS=async function(){if(!window.supabase?.createClient)return false;const db=window.JFS_ADMIN_SUPABASE||window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);window.JFS_ADMIN_SUPABASE=db;const r=await db.from('tenants').select('id,tenant_code,business_name,business_type,whatsapp,status,ai_enabled').eq('status','active').order('business_name');if(r.error){console.warn('JFS tenant load failed:',r.error.message);return false}const rows=r.data||[];const ids=rows.map(x=>x.id);let subs=[];if(ids.length){const s=await db.from('tenant_subscriptions').select('tenant_id,start_date,end_date,status,payment_status,subscription_plans(name)').in('tenant_id',ids).order('end_date',{ascending:false});if(!s.error)subs=s.data||[]}cache=rows.map(t=>{const s=subs.find(x=>x.tenant_id===t.id);return normalize(t,s?{...s,plan_name:s.subscription_plans?.name}:null)});save();if(typeof window.renderTenants==='function')window.renderTenants();window.dispatchEvent(new CustomEvent('jfs-tenants-updated',{detail:cache}));setTimeout(window.installFirmanWhatsApp,100);return true};
window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{window.installFirmanWhatsApp();window.JFS_REFRESH_TENANTS?.()},300));
})();