/* JFS AI — Canonical tenant data bridge v11.
   Supabase is the single source of truth. localStorage is cache-only and never seeds tenants. */
(function(){
'use strict';
const SUPABASE_URL='https://evtkeyfjgqwarsmlzrkh.supabase.co';
const SUPABASE_KEY='sb_publishable_7lGio_RVVgkVASYYyBHQIg_GvL-8ELD';
const KEY='jfs_ai_tenants_cache_v11';
const FIRMAN={name:'Mas Firman Pratama',tenantCode:'MAS-FIRMAN-PRATAMA',whatsapp1:'6281230633464',whatsapp2:'6285706050689',projectUrl:'https://jfsaitechnology.github.io/jfs-ai-platform/mas-firman-pratama/demo.html'};
let cache=[];
try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(raw))cache=raw}catch(e){cache=[]}
function save(){try{localStorage.setItem(KEY,JSON.stringify(cache))}catch(e){}}
function isFirman(t){return String(t?.tenantCode||t?.tenant_code||'').toUpperCase()==='MAS-FIRMAN-PRATAMA'||String(t?.name||t?.business_name||'').toLowerCase().includes('mas firman pratama')}
function normalize(t){return{id:t.id,tenantCode:t.tenant_code||t.tenantCode||'',name:t.business_name||t.name||'Unnamed Tenant',type:t.business_type||t.type||'UMKM',whatsapp:t.whatsapp||'',whatsapp1:isFirman(t)?FIRMAN.whatsapp1:(t.whatsapp||''),whatsapp2:isFirman(t)?FIRMAN.whatsapp2:'',status:String(t.status||'inactive').toUpperCase(),aiEnabled:!!t.ai_enabled,plan:t.plan_name||t.plan||'-',startedAt:t.start_date||t.startedAt||null,expiresAt:t.end_date||t.expiresAt||null,subscriptionStatus:t.subscription_status||t.subscriptionStatus||null,paymentStatus:t.payment_status||t.paymentStatus||null,projectUrl:isFirman(t)?FIRMAN.projectUrl:(t.project_url||t.projectUrl||'')}}
window.JFSTenantStore={key:KEY,all:()=>cache.slice(),get:id=>cache.find(t=>t.id===id),save:t=>{if(!t?.id)return t;const i=cache.findIndex(x=>x.id===t.id);if(i>=0)cache[i]=t;else cache.push(t);save();return t},replace:list=>{cache=Array.isArray(list)?list.slice():[];save();return cache.slice()},clearCache:()=>{cache=[];try{localStorage.removeItem(KEY)}catch(e){}return true}};
function waButtons(){return '<div class="jfs-wa-buttons" style="display:flex;gap:7px;flex-wrap:wrap;margin-top:10px"><a class="btn wa" target="_blank" rel="noopener noreferrer" href="https://wa.me/'+FIRMAN.whatsapp1+'?text=Halo%20Admin%20Mas%20Firman,%20saya%20ingin%20informasi%20lebih%20lanjut.">🟢 WA Admin 1</a><a class="btn wa" target="_blank" rel="noopener noreferrer" href="https://wa.me/'+FIRMAN.whatsapp2+'?text=Halo%20Admin%20Mas%20Firman,%20saya%20ingin informasi%20lebih%20lanjut.">🟢 WA Admin 2</a></div>'}
function projectButton(){return '<div class="jfs-project-buttons" style="display:flex;gap:7px;flex-wrap:wrap;margin-top:10px"><a class="btn primary" target="_blank" rel="noopener noreferrer" href="'+FIRMAN.projectUrl+'">🚀 Buka Project Mas Firman</a></div>'}
function installFirmanButtons(){document.querySelectorAll('.tenant').forEach(card=>{if(!/mas firman pratama/i.test(card.textContent))return;card.querySelector('.jfs-wa-buttons')?.remove();card.querySelector('.jfs-project-buttons')?.remove();const actions=card.querySelector('.actions');(actions||card).insertAdjacentHTML('beforeend',waButtons()+projectButton())})}
window.installFirmanWhatsApp=installFirmanButtons;
async function rpc(path){const r=await fetch(SUPABASE_URL+'/rest/v1/rpc/'+path,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json','Accept':'application/json'},body:'{}',mode:'cors',cache:'no-store'});const text=await r.text();let data;try{data=JSON.parse(text)}catch(e){throw new Error('Supabase response bukan JSON: '+text.slice(0,180))}if(!r.ok)throw new Error(data?.message||data?.hint||data?.details||JSON.stringify(data));return data}
function repaint(){if(typeof window.renderTenants==='function'){window.renderTenants('tenantList');window.renderTenants('tenantPageList')}setTimeout(installFirmanButtons,50);setTimeout(installFirmanButtons,250);setTimeout(installFirmanButtons,800)}
window.JFS_REFRESH_TENANTS=async function(){try{const data=await rpc('get_platform_tenants');if(!Array.isArray(data))throw new Error('Data tenant bukan array');const mapped=data.map(normalize);cache=mapped;save();repaint();window.dispatchEvent(new CustomEvent('jfs-tenants-updated',{detail:cache.slice()}));return true}catch(e){console.error('[JFS Tenant] refresh gagal; mempertahankan cache terakhir:',e);repaint();window.dispatchEvent(new CustomEvent('jfs-tenants-error',{detail:{message:e.message,cached:cache.length}}));return false}};
window.addEventListener('jfs-tenants-updated',repaint);
function installOfficialLogo(){const src='jfs-ai-logo.svg';document.querySelectorAll('.logo').forEach(el=>{if(el.tagName==='IMG'){el.src=src;el.removeAttribute('srcset');el.alt='JFS AI Technology';}else{el.innerHTML='<img src="'+src+'" alt="JFS AI Technology" style="width:100%;height:100%;object-fit:contain;display:block;border-radius:50%">';el.style.background='transparent';el.style.border='0';}});document.querySelectorAll('link[rel="icon"]').forEach(el=>el.href=src);}
window.installOfficialJFSLogo=installOfficialLogo;
window.addEventListener('DOMContentLoaded',function(){repaint();installOfficialLogo();setTimeout(function(){window.JFS_REFRESH_TENANTS()},500);setTimeout(installOfficialLogo,100);setTimeout(installOfficialLogo,700);const observer=new MutationObserver(function(){installFirmanButtons();installOfficialLogo()});observer.observe(document.body,{childList:true,subtree:true});setTimeout(function(){observer.disconnect()},15000)});
})();