/* Mas Firman tenant authentication / authorization layer with JFS AI SSO support. */
const SUPABASE_URL='https://evtkeyfjgqwarsmlzrkh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_7lGio_RVVgkVASYYyBHQIg_GvL-8ELD';
const TENANT_ID='f0098e1c-da0c-4411-8720-9c99a3cfb115';
const AUTH_STORAGE_KEY='jfs-ai-auth';
let _tenantClient,_mainClient;
async function supabaseModule(){return import('https://esm.sh/@supabase/supabase-js@2');}
async function getSupabase(){if(_tenantClient)return _tenantClient;const mod=await supabaseModule();_tenantClient=mod.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:AUTH_STORAGE_KEY}});return _tenantClient;}
async function getMainPlatformClient(){if(_mainClient)return _mainClient;const mod=await supabaseModule();_mainClient=mod.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return _mainClient;}
async function waitForAuthSession(supabase){for(let i=0;i<30;i++){const{data,error}=await supabase.auth.getSession();if(!error&&data?.session?.user?.id)return data.session;await new Promise(r=>setTimeout(r,250));}return null;}
async function getExistingSession(){const tenant=await getSupabase();let session=await waitForAuthSession(tenant);if(session)return{session,source:'tenant'};try{const main=await getMainPlatformClient();session=await waitForAuthSession(main);if(session){await tenant.auth.setSession({access_token:session.access_token,refresh_token:session.refresh_token});return{session,source:'main-platform-sso'};}}catch(e){console.warn('Main platform SSO unavailable',e)}return{session:null,source:null};}
async function getTenantAccess(){const supabase=await getSupabase();const existing=await getExistingSession();const session=existing.session;if(!session?.user)return{authenticated:false,authorized:false,user:null,membership:null,error:new Error('NO_SESSION'),source:null};let lastError=null;for(let i=0;i<8;i++){const{data,error}=await supabase.rpc('jfs_get_my_tenant_membership',{p_tenant_id:TENANT_ID});const membership=Array.isArray(data)?data[0]||null:data||null;if(!error&&membership?.is_active)return{authenticated:true,authorized:true,user:session.user,membership,error:null,source:existing.source};lastError=error||new Error('NO_TENANT');await new Promise(r=>setTimeout(r,350));}return{authenticated:true,authorized:false,user:session.user,membership:null,error:lastError,source:existing.source};}
async function signOutTenant(){const supabase=await getSupabase();await supabase.auth.signOut({scope:'local'});window.location.replace('../pages/login.html');}
async function requireTenantAccess(){const access=await getTenantAccess();if(!access.authenticated){const next=encodeURIComponent(window.location.href);window.location.replace(`../pages/login.html?next=${next}`);return null;}if(!access.authorized){console.error('Tenant authorization failed',{user:access.user?.id,email:access.user?.email,source:access.source,error:access.error});document.body.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;background:#07101f;color:#fff;font-family:Arial,sans-serif;padding:24px"><section style="max-width:560px;background:#101b2f;border:1px solid #263754;border-radius:18px;padding:32px;text-align:center"><div style="font-size:42px">🔒</div><h1>Akses Tenant Ditolak</h1><p style="color:#aebbd0">Sesi JFS AI ditemukan, tetapi akun belum memiliki membership aktif untuk tenant Mas Firman Pratama.</p><button onclick="location.href='../../index.html'" style="padding:12px 18px;border:0;border-radius:10px;cursor:pointer">Kembali ke JFS AI</button></section></main>`;return null;}window.__JFS_ACCESS_ROLE=String(access.membership?.role||'').toLowerCase();window.__JFS_SSO_SOURCE=access.source;const badge=document.createElement('div');badge.style.cssText='position:fixed;right:16px;bottom:16px;z-index:9999;display:flex;align-items:center;gap:8px;background:#101b2f;border:1px solid #29415f;color:#dce8f8;padding:8px 10px;border-radius:12px;font:12px Arial,sans-serif;box-shadow:0 10px 30px rgba(0,0,0,.25)';badge.innerHTML=`<span>● Tenant Secure${access.source==='main-platform-sso'?' · SSO':''}</span><button id="jfsTenantLogout" style="border:0;border-radius:8px;padding:6px 9px;cursor:pointer">Keluar</button>`;document.body.appendChild(badge);document.getElementById('jfsTenantLogout').addEventListener('click',signOutTenant);return access;}
window.JFSTenantAuth={getSupabase,getTenantAccess,requireTenantAccess,signOutTenant,tenantId:TENANT_ID,authStorageKey:AUTH_STORAGE_KEY};
