(async () => {
  const access = await window.JFSTenantAuth?.requireTenantAccess();
  if (!access) return;

  const TENANT_CODE='MAS-FIRMAN-PRATAMA';
  const fallback=window.JFS_CATALOG;
  let schedules=[], knowledge=[], automations=[], contacts=[], bookings=[], participants=[], payments=[], deliveries=[], events=[];
  let catalog={products:[],programs:fallback.programs};
  const $=id=>document.getElementById(id);
  const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
  const normalize=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
  const stop=new Set(['yang','dan','atau','untuk','dari','dengan','ini','itu','apa','saya','mau','bisa','kak','mas','ada','nya','di','ke','berapa','kapan','kelas','berikutnya']);
  const tokens=s=>normalize(s).split(' ').filter(x=>x.length>2&&!stop.has(x));
  const today=()=>new Date().toISOString().slice(0,10);
  function toast(m){const t=$('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2600)}
  window.toast=toast;
  function fmtDate(d){return d?new Date(d+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'}):'tanggal belum ditentukan'}
  function formatSchedule(s){const t=s.start_time?(s.start_time.slice(0,5)+(s.end_time?'–'+s.end_time.slice(0,5):'')):'waktu belum ditentukan';return `${s.title} — ${fmtDate(s.schedule_date)}, ${t} WIB${s.location?' · '+s.location:''}`}
  function findKnowledge(q,limit=4){const qt=tokens(q);return knowledge.map(x=>{const hay=normalize(`${x.title} ${x.category} ${x.content}`);let score=0;qt.forEach(t=>{if(hay.includes(t))score+=(normalize(x.title).includes(t)?4:1)});return {...x,_score:score}}).filter(x=>x._score>0).sort((a,b)=>b._score-a._score).slice(0,limit)}
  function scheduled(type){return schedules.filter(s=>s.status==='scheduled'&&s.program_type===type&&(!s.schedule_date||s.schedule_date>=today())).sort((a,b)=>(a.schedule_date||'9999').localeCompare(b.schedule_date||'9999'))[0]}
  function nextAMC(){return schedules.filter(s=>s.status==='scheduled'&&(!s.schedule_date||s.schedule_date>=today())).sort((a,b)=>(a.schedule_date||'9999').localeCompare(b.schedule_date||'9999'))[0]}

  async function sb(){return JFSTenantAuth.getSupabase()}
  async function loadAll(){
    const supabase=await sb();
    const [tenantRes,prodRes,kbRes,contactRes,bookingRes,scheduleRes,autoRes,partRes,payRes,delRes,eventRes]=await Promise.all([
      JFS_TENANT_SERVICE.getTenant(),JFS_TENANT_SERVICE.getProducts(),JFS_TENANT_SERVICE.getKnowledge(),
      supabase.from('jfs_contacts').select('id,name,phone,email,source,status,lead_score,lifecycle_stage,program_interest,created_at,updated_at').eq('tenant_id',JFSTenantAuth.tenantId).order('created_at',{ascending:false}),
      supabase.from('jfs_bookings').select('id,contact_id,service_name,booking_date,start_time,end_time,status,notes,created_at').eq('tenant_id',JFSTenantAuth.tenantId).order('created_at',{ascending:false}),
      supabase.from('jfs_amc_schedules').select('*').eq('tenant_id',JFSTenantAuth.tenantId).order('schedule_date',{ascending:true}),
      supabase.from('jfs_automations').select('*').eq('tenant_id',JFSTenantAuth.tenantId).order('created_at',{ascending:true}),
      supabase.from('jfs_amc_participants').select('*').eq('tenant_id',JFSTenantAuth.tenantId).order('created_at',{ascending:false}),
      supabase.from('jfs_amc_payments').select('*').eq('tenant_id',JFSTenantAuth.tenantId).order('created_at',{ascending:false}),
      supabase.from('jfs_amc_material_deliveries').select('*').eq('tenant_id',JFSTenantAuth.tenantId).order('created_at',{ascending:false}),
      supabase.from('jfs_analytics_events').select('id,event_type,channel,metadata,created_at').eq('tenant_id',JFSTenantAuth.tenantId).order('created_at',{ascending:false}).limit(50)
    ]);
    for(const r of [contactRes,bookingRes,scheduleRes,autoRes,partRes,payRes,delRes,eventRes]) if(r.error) throw r.error;
    catalog.products=(prodRes||[]).map(p=>({id:p.id,sku:p.sku,name:p.name,image:p.image_url||p.image_path||'',description:p.description||'',price:Number(p.price||0),category:p.category||''}));
    knowledge=kbRes||[]; contacts=contactRes.data||[]; bookings=bookingRes.data||[]; schedules=scheduleRes.data||[]; automations=autoRes.data||[]; participants=partRes.data||[]; payments=payRes.data||[]; deliveries=delRes.data||[]; events=eventRes.data||[];
    if(tenantRes?.business_name)document.title='JFS AI — '+tenantRes.business_name;
    renderAll();
  }

  function renderAll(){renderProducts();renderBooking();renderCRM();renderAlumni();renderAutomation();renderKnowledge();renderScheduleAdmin();renderAnalytics();updateHome();}
  function updateHome(){$('nlead').textContent=contacts.length;$('nhot').textContent=contacts.filter(x=>Number(x.lead_score||0)>=85).length;$('nparticipant').textContent=participants.length;$('nalumni').textContent=participants.filter(x=>['completed','alumni'].includes(String(x.registration_status||'').toLowerCase())).length}
  function renderProducts(){const el=$('prodGrid');el.innerHTML=catalog.products.length?catalog.products.map((p,i)=>`<div class="card product"><img src="${p.image}" alt="${p.name}"><h3>${p.name}</h3><div class="price">${money(p.price)}</div><button class="btn" onclick="detail(${i})">Lihat Detail</button></div>`).join(''):'<p class="muted">Belum ada produk aktif di Supabase.</p>'}
  window.detail=i=>{const p=catalog.products[i];if(!p)return;$('mt').textContent=p.name;$('mi').src=p.image;$('md').textContent=p.description;$('mp').textContent=money(p.price);$('modal').classList.add('show')};window.closeM=()=>$('modal').classList.remove('show');
  function renderBooking(){
    $('amcGrid').innerHTML=catalog.programs.slice(1).map(p=>`<div class="card amc"><img src="../assets/programs/amc-class.svg" alt="${p.name}"><h3>${p.name}</h3><p class="muted">Program ${p.type}</p><button class="btn" onclick="rprog.value='${p.name}'">Pilih</button></div>`).join('');
    const types=['Online','Reguler','Privat','Platinum'];$('scheduleCards').innerHTML=types.map(t=>{const s=scheduled(t);return `<div class="card"><b>AMC ${t}</b><p class="muted">${s?formatSchedule(s):'Belum ada jadwal terbaru.'}</p><small>${s?.queue_estimate||'Estimasi antrean 3–4 bulan'}</small></div>`}).join('');
  }
  function renderCRM(){
    $('crmTotal').textContent=contacts.length;$('crmHot').textContent=contacts.filter(x=>Number(x.lead_score||0)>=85).length;$('crmPaid').textContent=participants.filter(x=>x.payment_status==='paid').length;$('crmQueue').textContent=participants.filter(x=>x.queue_status==='waiting').length;
    const byId=Object.fromEntries(contacts.map(x=>[x.id,x]));
    const rows=[...participants.map(p=>({name:p.full_name,phone:p.phone,program:p.program_type,score:byId[p.contact_id]?.lead_score||0,status:p.registration_status,step:p.current_step,paid:p.payment_status,queue:p.queue_status})),...contacts.filter(c=>!participants.some(p=>p.contact_id===c.id)).map(c=>({name:c.name,phone:c.phone,program:c.program_interest||'-',score:c.lead_score,status:c.lifecycle_stage,step:'-',paid:'-',queue:'-'}))];
    const html=rows.length?rows.map(x=>`<div class="item"><b>${x.name||'-'}</b> · ${x.program||'-'} · Score ${x.score||0}<br><small>${x.phone||''} · Status: <b>${x.status||'lead'}</b> · Step: ${x.step} · Bayar: ${x.paid} · Antrean: ${x.queue}</small></div>`).join(''):'<p class="muted">Belum ada contact/lead.</p>';
    $('crmList').innerHTML=html;$('leadList').innerHTML=html;
  }
  function renderAlumni(){
    const alumni=participants.filter(p=>['completed','alumni'].includes(String(p.registration_status||'').toLowerCase()));const active=participants.length-alumni.length;const follow=automations.filter(a=>a.trigger_type==='participant_completed'&&a.is_active).length;
    $('alumniTotal').textContent=alumni.length;$('alumniActive').textContent=active;$('alumniCompleted').textContent=alumni.length;$('alumniFollowups').textContent=follow;
    $('alumniList').innerHTML=alumni.length?alumni.map(p=>`<div class="item"><b>${p.full_name}</b> · ${p.program_type}<br><small>${p.phone||''} · Selesai: ${fmtDate((p.updated_at||'').slice(0,10))}</small><br><button class="btn" onclick="wa('Halo ${encodeURIComponent(p.full_name)}, terima kasih sudah mengikuti AMC. Kami siap membantu program lanjutan.')">💬 Follow-up WhatsApp</button></div>`).join(''):'<div class="item">Belum ada peserta berstatus selesai/alumni. Peserta akan masuk otomatis setelah statusnya diselesaikan.</div>';
  }
  function renderAutomation(){
    $('automationList').innerHTML=automations.length?automations.map(a=>`<div class="item"><b>${a.name}</b><br><small>Trigger: ${a.trigger_type} · Action: ${a.action_type} · ${a.is_active?'AKTIF':'NONAKTIF'}</small><p>${a.config?.message||a.config?.material_title||a.config?.estimate||''}</p></div>`).join(''):'<div class="item">Belum ada workflow automation.</div>';
  }
  function renderKnowledge(){$('kview').innerHTML=knowledge.length?knowledge.map(x=>`<div class="item"><b>${x.title}</b><small style="display:block;opacity:.65">${x.category||'general'}</small><p>${x.content}</p></div>`).join(''):'<div class="item">Knowledge tenant belum tersedia.</div>'}
  function renderScheduleAdmin(){const can=['owner','admin'].includes(String(access.membership?.role||'').toLowerCase());const nav=document.querySelector("button[onclick=\"go('scheduleAdmin',this)\"]");if(nav)nav.style.display=can?'':'none';if(!can){$('scheduleAdminList').innerHTML='<div class="item">Akses hanya untuk owner/admin tenant.</div>';return}if(!schedules.length){$('scheduleAdminList').innerHTML='<div class="item">Belum ada jadwal.</div>';return}$('scheduleAdminList').innerHTML=schedules.map(s=>`<div class="item"><b>${s.program_type}</b> · ${s.title}<br><small>${formatSchedule(s)} · Antrean: ${s.queue_estimate||'3–4 bulan'} · Status: <b>${s.status}</b></small><p>${s.notes||''}</p><button class="btn" onclick="editSchedule('${s.id}')">Edit</button> <button class="btn" onclick="deleteSchedule('${s.id}')">Hapus</button></div>`).join('')}
  function renderAnalytics(){
    const leadCount=contacts.length, reg=participants.length, paid=participants.filter(p=>p.payment_status==='paid').length, alumni=participants.filter(p=>['completed','alumni'].includes(String(p.registration_status||'').toLowerCase())).length, pending=automations.filter(a=>a.is_active&&a.trigger_type==='participant_completed').length;
    $('aConversion').textContent=(leadCount?Math.round(reg/leadCount*100):0)+'%';$('aPayment').textContent=(reg?Math.round(paid/reg*100):0)+'%';$('aAlumni').textContent=(reg?Math.round(alumni/reg*100):0)+'%';$('aFollowup').textContent=pending;
    const stages=[['Leads',leadCount],['Pendaftar AMC',reg],['Sudah Bayar',paid],['Menunggu Antrean',participants.filter(p=>p.queue_status==='waiting').length],['Terjadwal',participants.filter(p=>p.schedule_id).length],['Selesai/Alumni',alumni]];$('analyticsFunnel').innerHTML=stages.map(([n,v])=>`<div class="item"><b>${n}</b><span style="float:right">${v}</span></div>`).join('');
    $('analyticsEvents').innerHTML=events.length?events.slice(0,10).map(e=>`<div class="item"><b>${e.event_type}</b> · ${e.channel||'web'}<br><small>${new Date(e.created_at).toLocaleString('id-ID')}</small></div>`).join(''):'<div class="item">Belum ada event analytics.</div>';
  }
  window.go=(id,btn)=>{document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));const p=$(id);if(p)p.classList.add('on');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));if(btn)btn.classList.add('on');if(id==='analytics')renderAnalytics();if(id==='alumni')renderAlumni();if(id==='automation')renderAutomation();window.scrollTo(0,0)};
  window.resetScheduleForm=()=>{['scheduleId','scheduleTitle','scheduleDate','scheduleLocation','scheduleUrl','scheduleQueue','scheduleNotes'].forEach(id=>$(id).value='');$('scheduleType').value='Online';$('scheduleStart').value='09:00';$('scheduleEnd').value='15:00';$('scheduleQueue').value='3–4 bulan';$('scheduleStatus').value='scheduled';$('scheduleFormTitle').textContent='Tambah Jadwal AMC'};
  window.editSchedule=id=>{const s=schedules.find(x=>x.id===id);if(!s)return;$('scheduleId').value=s.id;$('scheduleType').value=s.program_type;$('scheduleTitle').value=s.title||'';$('scheduleDate').value=s.schedule_date||'';$('scheduleStart').value=s.start_time?s.start_time.slice(0,5):'09:00';$('scheduleEnd').value=s.end_time?s.end_time.slice(0,5):'15:00';$('scheduleLocation').value=s.location||'';$('scheduleUrl').value=s.meeting_url||'';$('scheduleQueue').value=s.queue_estimate||'3–4 bulan';$('scheduleStatus').value=s.status||'draft';$('scheduleNotes').value=s.notes||'';$('scheduleFormTitle').textContent='Edit Jadwal AMC';window.go('scheduleAdmin')};
  window.saveSchedule=async()=>{if(!['owner','admin'].includes(String(access.membership?.role||'').toLowerCase()))return toast('Akses ditolak');const title=$('scheduleTitle').value.trim();if(!title)return toast('Judul kelas wajib diisi');const supabase=await sb();const payload={tenant_id:JFSTenantAuth.tenantId,program_type:$('scheduleType').value,title,schedule_date:$('scheduleDate').value||null,start_time:$('scheduleStart').value||null,end_time:$('scheduleEnd').value||null,location:$('scheduleLocation').value.trim()||null,meeting_url:$('scheduleUrl').value.trim()||null,queue_estimate:$('scheduleQueue').value.trim()||'3–4 bulan',is_public:$('scheduleStatus').value==='scheduled',status:$('scheduleStatus').value,notes:$('scheduleNotes').value.trim()||null,updated_at:new Date().toISOString()};try{const r=$('scheduleId').value?await supabase.from('jfs_amc_schedules').update(payload).eq('id',$('scheduleId').value).eq('tenant_id',JFSTenantAuth.tenantId):await supabase.from('jfs_amc_schedules').insert(payload);if(r.error)throw r.error;resetScheduleForm();await loadAll();toast('Jadwal AMC berhasil disimpan')}catch(e){console.error(e);toast('Gagal menyimpan jadwal: '+e.message)}};
  window.deleteSchedule=async id=>{if(!confirm('Hapus jadwal ini?'))return;const supabase=await sb();const{error}=await supabase.from('jfs_amc_schedules').delete().eq('id',id).eq('tenant_id',JFSTenantAuth.tenantId);if(error)return toast('Gagal menghapus: '+error.message);await loadAll();toast('Jadwal dihapus')};

  window.register=async()=>{const n=$('rn').value.trim(),phone=$('rp').value.trim(),email=$('re').value.trim(),pr=$('rprog').value;if(!n||!phone)return toast('Nama dan WhatsApp wajib diisi');try{const supabase=await sb();const{data,error}=await supabase.rpc('create_customer_booking',{p_tenant_code:TENANT_CODE,p_name:n,p_phone:phone,p_email:email,p_program_interest:pr,p_booking_date:today(),p_start_time:null,p_end_time:null,p_notes:'Pendaftaran AMC melalui dashboard'});if(error)throw error;await supabase.from('jfs_analytics_events').insert({tenant_id:JFSTenantAuth.tenantId,event_type:'registration_created',channel:'dashboard',metadata:{program:pr}});await loadAll();$('rn').value='';$('rp').value='';$('re').value='';toast('Pendaftaran tersimpan. Tim akan melanjutkan proses pembayaran/formulir.');console.log('registration',data)}catch(e){console.error(e);toast('Pendaftaran gagal: '+e.message)}};

  function aiAnswer(q){const z=normalize(q);if(/harga|biaya|bayar|4 500/.test(z))return 'Biaya kelas AMC adalah Rp4.500.000. Alur: daftar & bayar → isi formulir → menerima materi → menunggu antrean estimasi 3–4 bulan → kelas AMC pukul 09.00–15.00 bersama Pak Firman, peserta satu per satu.';if(/mekanisme|cara daftar|alur|langkah/.test(z))return 'Mekanisme AMC: 1) Daftar dan bayar Rp4.500.000, 2) isi formulir peserta, 3) materi dikirim untuk dipelajari, 4) menunggu antrean sekitar 3–4 bulan, 5) pelaksanaan kelas 09.00–15.00 dibimbing langsung Pak Firman, peserta satu per satu.';if(/jadwal|kapan|tanggal|kelas berikut/.test(z)){const s=nextAMC();return s?`Jadwal AMC berikutnya: ${formatSchedule(s)}. Estimasi antrean ${s.queue_estimate||'3–4 bulan'}.`:'Belum ada jadwal AMC terbaru yang dipublikasikan.'}if(/whatsapp|hubungi|admin|konsultasi/.test(z))return 'Silakan gunakan tombol WhatsApp Admin pada website atau halaman pendaftaran untuk melanjutkan konsultasi.';const hits=findKnowledge(q);if(hits.length)return hits[0].content;const p=catalog.products.find(x=>z.includes(normalize(x.name)));if(p)return `${p.name}: ${p.description||'Informasi produk tersedia di katalog.'} Harga ${money(p.price)}.`;return 'Saya belum menemukan jawaban spesifik di Knowledge Base Mas Firman. Silakan tanyakan tentang biaya, mekanisme, jadwal, pendaftaran, materi, atau buku AMC.'}
  window.ask=async()=>{const q=$('q').value.trim();if(!q)return;$('chat').innerHTML+=`<div class="msg me"></div>`;$('chat').lastElementChild.textContent=q;const answer=aiAnswer(q);$('chat').innerHTML+=`<div class="msg"></div>`;$('chat').lastElementChild.textContent=answer;$('q').value='';try{const supabase=await sb();const{data:conv}=await supabase.from('jfs_conversations').insert({tenant_id:JFSTenantAuth.tenantId,channel:'web',status:'open',last_message_at:new Date().toISOString()}).select('id').single();if(conv?.id){await supabase.from('jfs_messages').insert([{tenant_id:JFSTenantAuth.tenantId,conversation_id:conv.id,direction:'inbound',sender_type:'customer',content:q,ai_generated:false},{tenant_id:JFSTenantAuth.tenantId,conversation_id:conv.id,direction:'outbound',sender_type:'ai',content:answer,ai_generated:true}]);}await supabase.from('jfs_analytics_events').insert({tenant_id:JFSTenantAuth.tenantId,event_type:'ai_question',channel:'web',metadata:{question:q}})}catch(e){console.warn('AI logging skipped',e)}};
  window.wa=text=>window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank','noopener');
  try{await loadAll();toast('CRM · AI · Automation · Alumni · Analytics aktif');}catch(e){console.error(e);toast('Sebagian data belum dapat dimuat: '+e.message)}
})();
